package vn.muasamcong.downloader.model;

public enum BidStatus {
    TBMT_CANCELLED,
    INVITATION_OPEN,
    BIDDING_CLOSED,
    BID_OPENED,
    CONTRACTOR_SELECTION_RESULT_AVAILABLE,
    CONTRACT_INFORMATION_AVAILABLE
}
